[build]
  publish = "."

[[redirects]]
  from = "/catalog"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/about"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/visit"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/services"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
