'use server';

// Checkout / order persistence. This is a PUBLIC action (guests can order),
// so it must never trust client-supplied prices — it re-reads authoritative
// prices from the DB and computes every total server-side. Writes go through
// the service-role client (after server-side validation) so guest orders work
// regardless of RLS; the customer is linked when logged in.

import { randomUUID } from 'crypto';
import { headers } from 'next/headers';
import { revalidatePath } from 'next/cache';
import { getSupabaseAdmin } from './supabase/admin';
import { getCurrentUser, getSupabaseServer } from './supabase/server';
import type { MyOrder } from './types';
import { getCloverClient } from './clover';
import { assertAdmin } from './auth-guard';
import { PER_ITEM_LIMIT, FREE_SHIPPING_THRESHOLD, FLAT_SHIPPING, TAX_RATE, round2 } from './pricing';
import { ORDER_STATUSES, type OrderStatus } from './orderStatus';

export interface CheckoutItem {
  productId: string;
  quantity: number;
}

export interface ShippingDetails {
  fullName: string;
  address: string;
  city: string;
  state: string;
  zip: string;
}

export interface PlaceOrderResult {
  ok: boolean;
  orderNumber?: string;
  total?: number;
  error?: string;
  /** Clover charge id (mock_ch_… in phantom mode). */
  chargeId?: string;
  paymentMode?: 'mock' | 'live';
}

function orderNumber(prefix = 'TR'): string {
  return `${prefix}-${randomUUID().replace(/-/g, '').slice(0, 6).toUpperCase()}`;
}

export interface PlaceOrderOptions {
  /**
   * A second, separate card token (from a second createToken() call on the
   * same filled-in fields) used only to vault the card after the purchase
   * has already succeeded via `cardToken`. Best-effort — never blocks or
   * un-does the order if vaulting fails.
   */
  vaultCardToken?: string;
  /** Pay with a previously-saved card instead of a fresh token. */
  savedPaymentMethodId?: string;
  /**
   * One id per checkout attempt, generated by the browser. A double-submit
   * (double click, flaky network retry) with the same key resolves to the
   * order already created for it instead of charging the card again.
   */
  idempotencyKey?: string;
}

const PAYMENT_UNCONFIRMED_MESSAGE =
  'We couldn’t confirm your payment. Please don’t try again — we’ll check on it and contact you. ' +
  'If you need help, use the Contact page.';

// If this checkout attempt already created an order, report on that order
// instead of creating (and charging) a second one.
async function findExistingAttempt(
  supabase: NonNullable<ReturnType<typeof getSupabaseAdmin>>,
  idempotencyKey: string
): Promise<PlaceOrderResult | null> {
  const { data: existing } = await supabase
    .from('orders')
    .select('order_number, status, total, clover_order_id')
    .eq('idempotency_key', idempotencyKey)
    .maybeSingle();
  if (!existing) return null;
  if (existing.status === 'pending') {
    return { ok: false, error: PAYMENT_UNCONFIRMED_MESSAGE };
  }
  return {
    ok: true,
    orderNumber: existing.order_number,
    total: Number(existing.total),
    chargeId: existing.clover_order_id ?? undefined,
  };
}

export async function placeOrder(
  items: CheckoutItem[],
  shipping: ShippingDetails,
  /** Clover-hosted-field card token (client-side tokenized). Required in live mode. */
  cardToken?: string,
  opts?: PlaceOrderOptions
): Promise<PlaceOrderResult> {
  if (!items || items.length === 0) {
    return { ok: false, error: 'Your cart is empty.' };
  }

  const supabase = getSupabaseAdmin();

  // Fallback: no service-role key (e.g. local demo without it) — behave like
  // the old mock so checkout still completes, but don't persist anything.
  if (!supabase) {
    return { ok: true, orderNumber: orderNumber() };
  }

  try {
    const idempotencyKey = opts?.idempotencyKey?.slice(0, 100) || null;
    if (idempotencyKey) {
      const existing = await findExistingAttempt(supabase, idempotencyKey);
      if (existing) return existing;
    }

    // Clamp quantities to the per-item limit and de-dupe ids.
    const wanted = new Map<string, number>();
    for (const it of items) {
      const q = Math.min(PER_ITEM_LIMIT, Math.max(1, Math.floor(it.quantity)));
      wanted.set(it.productId, Math.min(PER_ITEM_LIMIT, (wanted.get(it.productId) ?? 0) + q));
    }
    const ids = [...wanted.keys()];

    // Authoritative product data (price/name/stock flag) straight from the DB.
    const { data: products, error: pErr } = await supabase
      .from('products')
      .select('id, name, price, is_out_of_stock')
      .in('id', ids);
    if (pErr) return { ok: false, error: pErr.message };
    if (!products || products.length === 0) {
      return { ok: false, error: 'None of the items could be found.' };
    }

    // Stock is gated on the admin-managed out-of-stock flag, not on the
    // quantity column — seeded quantities aren't reliable yet (most read 0).
    const unavailable = products.filter((p: { is_out_of_stock: boolean }) => p.is_out_of_stock);
    if (unavailable.length > 0) {
      const names = unavailable.map((p: { name: string }) => p.name).join(', ');
      return { ok: false, error: `Sorry, these items just sold out: ${names}. Please remove them from your cart.` };
    }

    const lineItems = products.map((p: { id: string; name: string; price: number | string }) => {
      const qty = wanted.get(p.id) ?? 1;
      const unit = Number(p.price);
      return {
        product_id: p.id,
        product_name: p.name,
        unit_price: unit,
        quantity: qty,
        lineTotal: unit * qty,
      };
    });

    const subtotal = round2(lineItems.reduce((s, l) => s + l.lineTotal, 0));
    const shippingCost = subtotal >= FREE_SHIPPING_THRESHOLD ? 0 : FLAT_SHIPPING;
    // Flat rate for our single Windsor, CA jurisdiction — see lib/pricing.ts.
    const tax = round2(subtotal * TAX_RATE);
    const total = round2(subtotal + shippingCost + tax);

    const user = await getCurrentUser();

    // Mock orders get a DEMO- number so they can be bulk-cleaned from the
    // admin dashboard (real orders use TR-).
    const clover = await getCloverClient();
    const number = orderNumber(clover.mode === 'mock' ? 'DEMO' : 'TR');
    const forwardedFor = (await headers()).get('x-forwarded-for');
    const clientIp = forwardedFor?.split(',')[0]?.trim();
    const amountCents = Math.round(total * 100);

    // Resolve a saved card before touching the DB so a bad id fails cleanly.
    let storedCard: { customerId: string; sourceId: string } | undefined;
    if (clover.mode === 'live' && opts?.savedPaymentMethodId && user) {
      // Confirmed by direct testing (not documented plainly anywhere): Clover
      // charges whatever card is on file when `source` is the CUSTOMER id
      // itself — see chargeStoredCard in lib/clover/live.ts.
      const { data: pm } = await supabase
        .from('payment_methods')
        .select('clover_source_id')
        .eq('id', opts.savedPaymentMethodId)
        .eq('customer_id', user.id) // manual ownership check: service-role bypasses RLS
        .maybeSingle();
      const { data: profile } = await supabase
        .from('profiles')
        .select('clover_customer_id')
        .eq('id', user.id)
        .maybeSingle();
      if (!pm || !profile?.clover_customer_id) {
        return { ok: false, error: 'Saved card not found.' };
      }
      storedCard = { customerId: profile.clover_customer_id, sourceId: pm.clover_source_id };
    } else if (clover.mode === 'live' && !cardToken) {
      return { ok: false, error: 'Payment could not be processed — missing card details.' };
    }

    // 1. Write the order as 'pending' — items, inventory log and stock
    //    decrement in one DB transaction — BEFORE charging. If this fails the
    //    customer is never charged; if it succeeds, every charge has an order.
    const { data: orderId, error: oErr } = await supabase.rpc('create_pending_order', {
      p_order_number: number,
      p_idempotency_key: idempotencyKey,
      p_customer_id: user?.id ?? null,
      p_subtotal: subtotal,
      p_tax: tax,
      p_shipping: shippingCost,
      p_total: total,
      p_shipping_address: shipping,
      p_items: lineItems.map(({ product_id, product_name, unit_price, quantity }) => ({
        product_id,
        product_name,
        unit_price,
        quantity,
      })),
    });
    if (oErr || !orderId) {
      // A concurrent submit of the same attempt won the unique key.
      if (idempotencyKey && oErr?.code === '23505') {
        const existing = await findExistingAttempt(supabase, idempotencyKey);
        if (existing) return existing;
      }
      return { ok: false, error: oErr?.message || 'Could not create your order.' };
    }

    // 2. Charge. The order id doubles as Clover's idempotency key, so the one
    //    retry below can never double-charge; a declined card gets a fresh
    //    order (and key) on the customer's next attempt.
    const charge = async () =>
      storedCard
        ? clover.chargeStoredCard({ amountCents, orderNumber: number, clientIp, idempotencyKey: orderId, ...storedCard })
        : clover.createCharge({ amountCents, orderNumber: number, source: cardToken, clientIp, idempotencyKey: orderId });
    let result = await charge();
    if (!result.ok && result.uncertain) result = await charge();

    if (!result.ok) {
      if (result.uncertain) {
        // The card may have been charged. Keep the pending order so staff can
        // reconcile it against Clover, and tell the customer not to retry.
        console.error(`[checkout] payment unconfirmed for ${number}: ${result.error}`);
        return { ok: false, error: PAYMENT_UNCONFIRMED_MESSAGE };
      }
      // Definitive decline: release the stock and remove the pending order.
      const { error: dErr } = await supabase.rpc('discard_pending_order', { p_order_id: orderId });
      if (dErr) console.error(`[checkout] could not discard declined order ${number}: ${dErr.message}`);
      return { ok: false, error: result.error || 'Payment could not be processed.' };
    }

    // 3. Paid — move the order into fulfillment. If this write fails the
    //    customer has still paid and the order still exists (as 'pending'),
    //    so report success and leave it for staff to advance.
    const { error: uErr } = await supabase
      .from('orders')
      .update({ status: 'processing', clover_order_id: result.chargeId ?? null })
      .eq('id', orderId);
    if (uErr) {
      console.error(`[checkout] ${number} paid (charge ${result.chargeId}) but status update failed: ${uErr.message}`);
    }

    // Vaulting a NEW card only applies when we didn't just pay with an
    // already-saved one. Best-effort only — the order is already placed.
    if (clover.mode === 'live' && opts?.vaultCardToken && user && !storedCard) {
      const { data: profile } = await supabase
        .from('profiles')
        .select('clover_customer_id')
        .eq('id', user.id)
        .maybeSingle();
      const [firstName, ...rest] = shipping.fullName.trim().split(/\s+/);
      const saved = await clover.saveCard({
        cardToken: opts.vaultCardToken,
        email: user.email ?? '',
        firstName: firstName || shipping.fullName,
        lastName: rest.join(' '),
        existingCustomerId: profile?.clover_customer_id || undefined,
      });
      // v1 supports one saved card per customer (matches Clover's
      // replace-on-save semantics), so clear any prior row first.
      if (saved.ok && saved.customerId && saved.sourceId) {
        await supabase.from('profiles').update({ clover_customer_id: saved.customerId }).eq('id', user.id);
        await supabase.from('payment_methods').delete().eq('customer_id', user.id);
        await supabase.from('payment_methods').insert({
          customer_id: user.id,
          clover_source_id: saved.sourceId,
          brand: saved.brand || '',
          last4: saved.last4 || '',
          exp_month: saved.expMonth ?? null,
          exp_year: saved.expYear ?? null,
          is_default: true,
        });
      }
    }

    revalidatePath('/account');
    revalidatePath('/admin');
    revalidatePath('/admin/orders');
    return {
      ok: true,
      orderNumber: number,
      total,
      chargeId: result.chargeId,
      paymentMode: clover.mode,
    };
  } catch (e) {
    return { ok: false, error: e instanceof Error ? e.message : 'Order failed.' };
  }
}

/**
 * Bulk-delete demo orders (those with a DEMO- number, created by the phantom
 * Clover in mock mode). Admin-only. Never touches real (TR-) orders.
 * order_items cascade on delete; inventory_transactions are matched by the
 * order number (reference_id) and removed too.
 */
export async function deleteDemoOrders(): Promise<{
  ok: boolean;
  deleted?: number;
  error?: string;
}> {
  await assertAdmin();
  const supabase = getSupabaseAdmin();
  if (!supabase) return { ok: false, error: 'Supabase service key not configured.' };
  try {
    const { data: demo, error: qErr } = await supabase
      .from('orders')
      .select('id, order_number')
      .like('order_number', 'DEMO-%');
    if (qErr) return { ok: false, error: qErr.message };
    if (!demo || demo.length === 0) return { ok: true, deleted: 0 };

    const ids = demo.map((o: { id: string }) => o.id);
    const numbers = demo.map((o: { order_number: string }) => o.order_number);

    await supabase.from('inventory_transactions').delete().in('reference_id', numbers);
    const { error: dErr } = await supabase.from('orders').delete().in('id', ids);
    if (dErr) return { ok: false, error: dErr.message };

    revalidatePath('/admin');
    revalidatePath('/admin/orders');
    return { ok: true, deleted: ids.length };
  } catch (e) {
    return { ok: false, error: e instanceof Error ? e.message : 'Failed.' };
  }
}

const RESTOCKING_STATUSES: OrderStatus[] = ['canceled', 'refunded'];

/**
 * Admin-only: move an order through its fulfillment lifecycle. Moving *into*
 * canceled/refunded from any other status restocks the order's items (and
 * logs an inventory_transactions row per item) — moving between the two
 * terminal statuses, or re-saving the same one, never double-restocks.
 * Reversing out of canceled/refunded back to an active status does NOT
 * re-deduct stock; that's a rare manual-correction case left for an admin to
 * true up by hand if it ever comes up.
 */
export async function updateOrderStatus(
  orderId: string,
  status: OrderStatus
): Promise<{ ok: boolean; error?: string }> {
  await assertAdmin();
  if (!ORDER_STATUSES.includes(status)) {
    return { ok: false, error: 'Invalid status.' };
  }
  const supabase = await getSupabaseServer();
  if (!supabase) return { ok: false, error: 'Not available.' };

  const { data: order } = await supabase
    .from('orders')
    .select('order_number, status')
    .eq('id', orderId)
    .maybeSingle();
  if (!order) return { ok: false, error: 'Order not found.' };

  const alreadyRestocked = RESTOCKING_STATUSES.includes(order.status as OrderStatus);
  if (RESTOCKING_STATUSES.includes(status) && !alreadyRestocked) {
    const user = await getCurrentUser();
    const { data: items } = await supabase
      .from('order_items')
      .select('product_id, quantity')
      .eq('order_id', orderId);

    // Stock RPCs are service-role only; the caller is already verified admin.
    const admin = getSupabaseAdmin();
    if (!admin) return { ok: false, error: 'Supabase service key not configured.' };
    for (const item of (items ?? []) as { product_id: string | null; quantity: number }[]) {
      if (!item.product_id) continue;
      const { error: sErr } = await admin.rpc('adjust_stock', {
        p_product_id: item.product_id,
        p_delta: item.quantity,
        p_reason: 'return',
        p_reference_id: order.order_number,
        p_created_by: user?.id ?? null,
      });
      if (sErr) return { ok: false, error: sErr.message };
    }
  }

  const { error } = await supabase.from('orders').update({ status }).eq('id', orderId);
  if (error) return { ok: false, error: error.message };

  revalidatePath('/admin/orders');
  revalidatePath('/admin');
  revalidatePath('/account');
  return { ok: true };
}

/** The signed-in customer's own orders (newest first), with line items.
 *  RLS ("orders self select") restricts this to the caller's own orders. */
export async function getMyOrders(): Promise<MyOrder[]> {
  const user = await getCurrentUser();
  if (!user) return [];
  const supabase = await getSupabaseServer();
  if (!supabase) return [];
  const { data, error } = await supabase
    .from('orders')
    .select('order_number, status, total, placed_at, order_items(product_name, quantity, unit_price)')
    .eq('customer_id', user.id)
    .order('placed_at', { ascending: false });
  if (error || !data) return [];
  return (data as Array<{
    order_number: string;
    status: string;
    total: number | string;
    placed_at: string;
    order_items: Array<{ product_name: string; quantity: number; unit_price: number | string }> | null;
  }>).map((o) => ({
    orderNumber: o.order_number,
    status: o.status,
    total: Number(o.total),
    placedAt: o.placed_at,
    items: (o.order_items ?? []).map((it) => ({
      name: it.product_name,
      quantity: it.quantity,
      unitPrice: Number(it.unit_price),
    })),
  }));
}

