window.TopRatedDB = {
  updatedAt: "2026-05-07T12:00:00-07:00",
  products: [
    {
      id: "pokemon-151-booster-bundle",
      sku: "PKM-151-BUNDLE",
      name: "Pokemon Scarlet & Violet 151 Booster Bundle",
      type: "packaged",
      category: "Pokemon sealed",
      brand: "Pokemon",
      price: 54.99,
      compareAt: 59.99,
      stock: 9,
      status: "Fast mover",
      image: "https://tcgplayer-cdn.tcgplayer.com/product/517045_in_1000x1000.jpg",
      sourceUrl: "https://www.tcgplayer.com/search/pokemon/product?productLineName=pokemon&q=151%20booster%20bundle",
      tags: ["sealed", "booster", "pokemon", "tcg"],
      attributes: { set: "Scarlet & Violet 151", format: "Booster Bundle", condition: "Sealed" },
      description: "Six-pack sealed Pokemon bundle for collectors chasing the original 151 lineup.",
      featured: 1,
    },
    {
      id: "pokemon-mega-evolution-etb",
      sku: "PKM-MEGA-ETB",
      name: "Pokemon Mega Evolution Elite Trainer Box",
      type: "packaged",
      category: "Pokemon sealed",
      brand: "Pokemon",
      price: 74.99,
      stock: 6,
      status: "New drop",
      image: "https://tcgplayer-cdn.tcgplayer.com/product/644282_in_1000x1000.jpg",
      sourceUrl: "https://www.tcgplayer.com/search/pokemon/product?productLineName=pokemon&q=mega%20evolution%20elite%20trainer%20box",
      tags: ["sealed", "etb", "pokemon"],
      attributes: { format: "Elite Trainer Box", condition: "Sealed" },
      description: "A premium sealed box modeled after the high-visibility Pokemon wall inventory.",
      featured: 2,
    },
    {
      id: "pokemon-surging-sparks-sleeved",
      sku: "PKM-SURGING-SLEEVE",
      name: "Pokemon Surging Sparks Sleeved Booster Pack",
      type: "packaged",
      category: "Pokemon packs",
      brand: "Pokemon",
      price: 8.99,
      stock: 28,
      status: "In stock",
      image: "https://tcgplayer-cdn.tcgplayer.com/product/589984_in_1000x1000.jpg",
      sourceUrl: "https://www.tcgplayer.com/search/pokemon/product?productLineName=pokemon&q=surging%20sparks%20sleeved%20booster",
      tags: ["pack", "pokemon", "sealed"],
      attributes: { set: "Surging Sparks", format: "Sleeved Booster", condition: "Sealed" },
      description: "Single sealed booster for quick counter pickups and casual ripping.",
      featured: 7,
    },
    {
      id: "one-piece-op-09-booster-box",
      sku: "OP-09-BOX",
      name: "One Piece OP-09 Booster Box",
      type: "packaged",
      category: "TCG sealed",
      brand: "Bandai",
      price: 119.99,
      stock: 4,
      status: "Limited",
      image: "https://tcgplayer-cdn.tcgplayer.com/product/579997_in_1000x1000.jpg",
      sourceUrl: "https://www.tcgplayer.com/search/one-piece-card-game/product?q=op-09%20booster%20box",
      tags: ["sealed", "one piece", "anime"],
      attributes: { set: "OP-09", format: "Booster Box", condition: "Sealed" },
      description: "Anime TCG sealed inventory inspired by the One Piece product visible in the shop.",
      featured: 4,
    },
    {
      id: "topps-chrome-baseball-hobby",
      sku: "TOPPS-CHROME-HOBBY",
      name: "Topps Chrome Baseball Hobby Box",
      type: "packaged",
      category: "Sports wax",
      brand: "Topps",
      price: 199.99,
      stock: 3,
      status: "In stock",
      image: "https://tcgplayer-cdn.tcgplayer.com/product/565822_in_1000x1000.jpg",
      sourceUrl: "https://www.topps.com/",
      tags: ["baseball", "sealed", "hobby box"],
      attributes: { sport: "Baseball", format: "Hobby Box", condition: "Sealed" },
      description: "Chrome baseball hobby product for rookie chases, refractors, and autograph hunts.",
      featured: 9,
    },
    {
      id: "ultra-pro-toploaders-25",
      sku: "SUP-TOPLOAD-25",
      name: "Ultra Pro 3x4 Top Loaders 25ct",
      type: "packaged",
      category: "Supplies",
      brand: "Ultra Pro",
      price: 5.99,
      stock: 40,
      status: "In stock",
      image: "https://tcgplayer-cdn.tcgplayer.com/product/173782_in_1000x1000.jpg",
      sourceUrl: "https://www.ultrapro.com/",
      tags: ["supplies", "protection", "toploaders"],
      attributes: { format: "25 count", condition: "New" },
      description: "Rigid holders for hits, autos, rookies, and cards headed into a trade binder.",
      featured: 12,
    },
    {
      id: "ultra-pro-sleeves-100",
      sku: "SUP-SLEEVES-100",
      name: "Ultra Pro Soft Sleeves 100ct",
      type: "packaged",
      category: "Supplies",
      brand: "Ultra Pro",
      price: 2.99,
      stock: 75,
      status: "In stock",
      image: "https://tcgplayer-cdn.tcgplayer.com/product/170651_in_1000x1000.jpg",
      sourceUrl: "https://www.ultrapro.com/",
      tags: ["supplies", "sleeves", "protection"],
      attributes: { format: "100 count", condition: "New" },
      description: "The everyday protection item every pack ripper grabs before opening wax.",
      featured: 14,
    },
    {
      id: "charizard-ex-sir-151",
      sku: "PKM-151-199",
      name: "Charizard ex Special Illustration Rare",
      type: "collectible",
      category: "Raw singles",
      brand: "Pokemon",
      price: 149.99,
      stock: 1,
      status: "Showcase",
      image: "https://images.pokemontcg.io/sv3pt5/199_hires.png",
      sourceUrl: "https://pokemontcg.io/",
      tags: ["pokemon", "raw", "single", "charizard"],
      attributes: { set: "Scarlet & Violet 151", number: "199/165", condition: "Near Mint" },
      description: "High-demand raw Pokemon showcase card with in-store condition review recommended.",
      featured: 3,
    },
    {
      id: "pikachu-surging-sparks-sir",
      sku: "PKM-SV8-238",
      name: "Pikachu ex Special Illustration Rare",
      type: "collectible",
      category: "Raw singles",
      brand: "Pokemon",
      price: 249.99,
      stock: 1,
      status: "Showcase",
      image: "https://images.pokemontcg.io/sv8/238_hires.png",
      sourceUrl: "https://pokemontcg.io/",
      tags: ["pokemon", "raw", "single", "pikachu"],
      attributes: { set: "Surging Sparks", number: "238/191", condition: "Near Mint" },
      description: "Bright chase-card listing for collectors browsing premium Pokemon singles.",
      featured: 5,
    },
    {
      id: "giratina-vstar-gg70",
      sku: "PKM-GG70",
      name: "Giratina VSTAR GG70 PSA 10",
      type: "collectible",
      category: "Graded Pokemon",
      brand: "Pokemon",
      price: 329.99,
      stock: 1,
      status: "Graded",
      image: "assets/4242.JPG",
      sourceUrl: "https://pokemontcg.io/",
      tags: ["pokemon", "graded", "psa", "slab"],
      attributes: { set: "Crown Zenith", grade: "PSA 10", condition: "Gem Mint" },
      description: "Example graded Pokemon slab for the showcase case experience.",
      featured: 6,
    },
    {
      id: "shohei-ohtani-rookie-psa9",
      sku: "MLB-OHTANI-PSA9",
      name: "Shohei Ohtani Rookie PSA 9",
      type: "collectible",
      category: "Graded sports",
      brand: "Topps",
      price: 189.99,
      stock: 1,
      status: "Showcase",
      image: "assets/4215.JPG",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Shohei_Ohtani_(52210315155)_(cropped).jpg",
      tags: ["baseball", "graded", "rookie", "psa"],
      attributes: { sport: "Baseball", grade: "PSA 9", condition: "Mint" },
      description: "Graded baseball example based on the slab-heavy sports display cases.",
      featured: 8,
    },
    {
      id: "michael-jordan-insert-psa8",
      sku: "NBA-JORDAN-PSA8",
      name: "Michael Jordan Insert PSA 8",
      type: "collectible",
      category: "Graded sports",
      brand: "Upper Deck",
      price: 249.99,
      stock: 1,
      status: "Showcase",
      image: "assets/4226.JPG",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Michael_Jordan_in_2014.jpg",
      tags: ["basketball", "graded", "jordan", "psa"],
      attributes: { sport: "Basketball", grade: "PSA 8", condition: "Near Mint-Mint" },
      description: "Basketball slab-style listing inspired by the lit showcase case.",
      featured: 10,
    },
    {
      id: "deebo-samuel-auto-patch",
      sku: "NFL-DEEBO-AUTO",
      name: "Deebo Samuel Autograph Patch",
      type: "collectible",
      category: "Autographs",
      brand: "Panini",
      price: 79.99,
      stock: 1,
      status: "Showcase",
      image: "assets/4231.JPG",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Deebo_Samuel_(51475738717).jpg",
      tags: ["football", "auto", "patch", "49ers"],
      attributes: { sport: "Football", format: "Autograph patch", condition: "Near Mint" },
      description: "Football autograph card example riffing on the 49ers memorabilia wall.",
      featured: 11,
    },
    {
      id: "top-rated-logo-hoodie",
      sku: "TR-HOODIE-BLK",
      name: "Top Rated Logo Hoodie",
      type: "packaged",
      category: "Apparel",
      brand: "Top Rated",
      price: 49.99,
      stock: 16,
      status: "In stock",
      image: "assets/4214.JPG",
      sourceUrl: "about.html",
      tags: ["apparel", "shop merch", "hoodie"],
      attributes: { sizes: "S-XXL", color: "Black / gray", condition: "New" },
      description: "Shop merch inspired by the black and gray hoodies hanging under the jerseys.",
      featured: 13,
    },
  ],
};
